# Perch Current — Quiet accents
mode = "dark"
accent = "#D3E880"
background = "#273D36"
dark_background = "#21352E"
darker_background = "#1C2E28"
lighter_background = "#354E43"
foreground = "#EFEAD8"
dark_foreground = "#B2C5B4"
light_foreground = "#F3EFDF"
bright_foreground = "#F7F2E2"
muted = "#B2C5B4"
structure = "#40584C"
structure_active = "#52715D"
selection = "#354E43"
selection_background = "#354E43"
selection_foreground = "#EFEAD8"
red = "#F4A790"
yellow = "#F0D28C"
orange = "#F0D28C"
green = "#B9DB93"
cyan = "#8FDEBC"
blue = "#A0DCCE"
magenta = "#D0BCDA"
purple = "#D0BCDA"
brown = "#D3B992"
bright_red = "#FFC0AC"
bright_yellow = "#F6DEA5"
bright_green = "#CCE9AA"
bright_cyan = "#AFEACE"
bright_blue = "#B9E9DF"
bright_magenta = "#E0CFE8"
hyprland_active_border = "#AEBF70"
hyprland_inactive_border = "#52715D"
theme_type = "dark"
