[colors-dark]
foreground=EFEAD8
background=273D36
selection-foreground=EFEAD8
selection-background=354E43

cursor=273D36 D3E880

regular0=273D36
regular1=F4A790
regular2=B9DB93
regular3=F0D28C
regular4=A0DCCE
regular5=D0BCDA
regular6=8FDEBC
regular7=EFEAD8

bright0=B2C5B4
bright1=FFC0AC
bright2=CCE9AA
bright3=F6DEA5
bright4=B9E9DF
bright5=E0CFE8
bright6=AFEACE
bright7=F7F2E2

# Apply translucency to default-color cells, including Neovim Normal.
alpha=0.92
alpha-mode=matching
