background = #273D36
foreground = #EFEAD8
cursor-color = #D3E880
selection-background = #354E43
selection-foreground = #EFEAD8

palette = 0=#273D36
palette = 1=#F4A790
palette = 2=#B9DB93
palette = 3=#F0D28C
palette = 4=#A0DCCE
palette = 5=#D0BCDA
palette = 6=#8FDEBC
palette = 7=#EFEAD8
palette = 8=#B2C5B4
palette = 9=#FFC0AC
palette = 10=#CCE9AA
palette = 11=#F6DEA5
palette = 12=#B9E9DF
palette = 13=#E0CFE8
palette = 14=#AFEACE
palette = 15=#F7F2E2

background-opacity = 0.92
