foreground #EFEAD8
background #273D36
selection_foreground #EFEAD8
selection_background #354E43

cursor #D3E880
cursor_text_color #273D36

active_border_color #D3E880
active_tab_background #354E43
active_tab_foreground #D3E880

color0 #273D36
color1 #F4A790
color2 #B9DB93
color3 #F0D28C
color4 #A0DCCE
color5 #D0BCDA
color6 #8FDEBC
color7 #EFEAD8
color8 #B2C5B4
color9 #FFC0AC
color10 #CCE9AA
color11 #F6DEA5
color12 #B9E9DF
color13 #E0CFE8
color14 #AFEACE
color15 #F7F2E2

background_opacity 0.92
